### ISSUE TITLE
BrokenBarHCollection has been removed from matplotlib in 3.7

### ISSUE THREAD

**Issue by martinResearch** [mir-evaluation/mir_eval#391]
mir_eval.display.piano_roll does not work for matplotlib>=3.7 because it uses BrokenBarHCollection that has been remove in  matplotlib 3.7 ( see https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html)

**Comment by craffel** [comment]
Should have been fixed in #380, display no longer used BrokenBarHCollection
